[package]
name = "restaking"
version = "1.0.0"
authors = []

[addresses]
aptos_framework = "0x1"
deployer = "_"
restaking = "_"

[dev-addresses]
deployer = "0xcafe"
restaking = "0xc3bb8488ab1a5815a9d543d7e41b0e0df46a7396f89b22821f07a4362f75ddc5"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
